### ISSUE TITLE
Zone IDs shifted.

### ISSUE THREAD

**Issue by eLiidyr** [MurphyCodes/FFxi-Navmesh-Builder#6]
**Describe the bug**
Recent update shifted some zone resources.

**To Reproduce**
Rebuild all the zones, and the zone will be incorrect.

**Expected behaviour**
Zone names should match the Zone ID.

**Corrected Zones.**
I believe this is the corrected values. _(d_ms.cs)_
`
private readonly List<int> _ignore = new()
{
    286,
    199,
    210,
    214,
    219,
};
`

**Comment by MurphyCodes** [comment]
Should be fixed, for some reason I had removed the part for checking if zone name is null or not.
Thanks for the heads up.

Those ID's are now named, 

`    case 199:
                                            text = $@"Mog House 1";
                                            break;

                                        case 210:
                                            text = $@"GM Home";
                                            break;

                                        case 214:
                                            text = $@"Mog House 2";
                                            break;

                                        case 219:
                                            text = $@"Mog House 3";
                                            break;

                                        case 286:
                                            text = $@"Unimplemented";
                                            break;`   

I've not checked out which mog house is which, so just called them 1,2 and 3.

Regards,

xen
